<?php

namespace App\Models;

use App\Traits\FormatDate;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Log;

class OrderAfterSale extends Model
{
    use HasFactory;
    use FormatDate;

    protected $fillable = [
        'user_id', 'order_id', 'order_item_id', 'type', 'price', 'after_status', 'reason', 'no'
    ];

    public const TYPE_REFUND = 1;
    public const TYPE_REFUND_AND_SALES = 2;

    public static $typeMap = [
        self::TYPE_REFUND => '仅退款',
        self::TYPE_REFUND_AND_SALES => '退货退款'
    ];

    public const ORDER_PREFIX = 'SH';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($order) {
            if (is_null($order->no)) {
                $order->no = static::findAvailableNo();
                if (!$order->no) {
                    return false;
                }
            }
        });
    }

    public static function findAvailableNo()
    {
        // 订单流水号前缀
        $prefix = date('YmdHis');
        // 随机生成 6 位的数字
        $no = self::ORDER_PREFIX . $prefix . str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);
        // 判断是否已经存在
        if (!static::query()->where('order_no', $no)->exists()) {
            return $no;
        }
        Log::warning(sprintf('find order no failed'));

        return false;
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
}
